### ISSUE TITLE
Calling wrong commands on Windows

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI2#52]
DUI2 in CCP4 9.0 is trying to call e.g. `dials.import.exe` on Windows, but this does not exist. The correct command is `dials.import.bat`

**Comment by luisodls** [comment]
cannot tes for the moment, we need to fix the launchimg problem first
 this is the message it shows me on console if I try to run Dui2 from Windows:


```
C:\Users\robert\Desktop>ccp4-python c:\Users\robert\Downloads\DUI2-master\DUI2-master\src\run_dui2.py
Traceback (most recent call last):
  File "C:\Users\robert\CCP4-9\CCP4\Python39\lib\site-packages\boost_adaptbx\boost\python.py", line 22, in import_ext
    try: mod = __import__(name)
ImportError: DLL load failed while importing boost_python_meta_ext: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\robert\Downloads\DUI2-master\DUI2-master\src\run_dui2.py", line 5, in <module>
    from dui2.all_local import main
  File "c:\Users\robert\Downloads\DUI2-master\DUI2-master\src\dui2\all_local.py", line 2, in <module>
    from dui2.server import run_server
  File "c:\Users\robert\Downloads\DUI2-master\DUI2-master\src\dui2\server\run_server.py", line 28, in <module>
    from dui2.server import multi_node
  File "c:\Users\robert\Downloads\DUI2-master\DUI2-master\src\dui2\server\multi_node.py", line 28, in <module>
    from dui2.server.data_n_json import get_info_data, spit_out
  File "c:\Users\robert\Downloads\DUI2-master\DUI2-master\src\dui2\server\data_n_json.py", line 29, in <module>
    from dials.command_line.find_spots import phil_scope as phil_scope_find_spots
  File "C:\Users\robert\CCP4-9\CCP4\Python39\lib\site-packages\dials\command_line\find_spots.py", line 9, in <module>
    from dxtbx.model import ExperimentList
  File "C:\Users\robert\CCP4-9\CCP4\Python39\lib\site-packages\dxtbx\model\__init__.py", line 10, in <module>
    import boost_adaptbx.boost.python
  File "C:\Users\robert\CCP4-9\CCP4\Python39\lib\site-packages\boost_adaptbx\boost\python.py", line 40, in <module>
    ext = import_ext("boost_python_meta_ext")
  File "C:\Users\robert\CCP4-9\CCP4\Python39\lib\site-packages\boost_adaptbx\boost\python.py", line 31, in import_ext
    raise ImportError(
ImportError: __import__("boost_python_meta_ext"): DLL load failed while importing boost_python_meta_ext: The specified module could not be found.
  sys.path:
    c:\Users\robert\Downloads\DUI2-master\DUI2-master\src
    C:\Users\robert\CCP4-9\CCP4\Python39\python39.zip
    C:\Users\robert\CCP4-9\CCP4\Python39\DLLs
    C:\Users\robert\CCP4-9\CCP4\Python39\lib
    C:\Users\robert\CCP4-9\CCP4\Python39
    C:\Users\robert\CCP4-9\CCP4\Python39\lib\site-packages
    C:\Users\robert\CCP4-9\CCP4\Python39\lib\site-packages\win32
    C:\Users\robert\CCP4-9\CCP4\Python39\lib\site-packages\win32\lib
    C:\Users\robert\CCP4-9\CCP4\Python39\lib\site-packages\Pythonwin

```

**Comment by luisodls** [comment]
fixed and tested
